[package]
name = "asisten_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
rfd = "0.12"
sysinfo = "=0.33.1"
nix = "0.29.0"
clap = "4.5.28"
serde = { version = "1.0" , features = ["derive"] }
serde_json = "1.0.138"
chrono = "0.4.39"
lazy_static = "1.5.0"